### ISSUE TITLE
Not working with new Spectrum TV app

### ISSUE THREAD

**Issue by compcandy** [redlee90/Hide-USB-Debugging-Mode#1]
The newest version of the Spectrum TV app (as of 2/23/2017) still detects that USB debugging is enabled.

**Comment by redlee90** [comment]
Hi, Did you tick the checkbox for the new "Spectrum TV" in the app settings? I tested on my own device and it works just fine.

**Comment by compcandy** [comment]
Yes, I have both versions of the Spectrum TV app and I checked both just in case. The new Spectrum TV app still gives me the pop-up and won't let me use it. It could be a device specific problem. I'm using a Motorola Z Force from Verizon.

**Comment by redlee90** [comment]
What if you uncheck the old one and only leave the new one checked? Or if you uninstall the old one and keep the new one only? I tested with the newest version (Feb 23 update) on my rooted Samsung galaxy note 5 with latest Xposed framework and it didn't pop.

**Comment by compcandy** [comment]
Than you. I tried to uncheck the old Spectrum app and then removed it. It still didn't work, unfortunately.

**Comment by redlee90** [comment]
Hi, Can you please post the log from Xposed installer? Thanks

**Comment by compcandy** [comment]
Oh my God. I totally forgot that I could not successfully install the Xposed framework. It won't work on my phone. I'm sorry. I totally wasted your time. I need more sleep.

**Comment by redlee90** [comment]
Haha, no worries, it happens. Get some sleep :)
